const os=require("os")
const my=require("./data/mymodule.js")
console.log(os.arch())
console.log(os.cpus())
console.log(os.freemem())
console.log(os.totalmem())
console.log(os.type())
console.log(os.release())
console.log(my.dummy)
my.fun1("peter")