const express=require('express')
const server=express()
const bp=require("body-parser")
server.use(bp.json())
const register=require('./routes/authentication/signUp')
const signin=require('./routes/authentication/signin')
server.use('/',register)
server.use('/',signin)
server.listen(3001,()=>console.log('server started'))