const express=require('express')
const server=express()
const bp=require("body-parser")
server.use(bp.json())
const createUser=require('./routes/contact manager/createUser')
const findUser=require('./routes/contact manager/findUser')
const updateUser=require('./routes/contact manager/updateUser')
const deleteUser=require('./routes/contact manager/deleteUser')
server.use('/contacts',createUser)
server.use('/',findUser)
server.use('/',updateUser)
server.use('/',deleteUser)

server.listen(3001,()=>console.log('server started'))