const express=require('express')
const server=express()
const bp=require("body-parser")
server.use(bp.json())
const createUser=require('./routes/createUser')
const findUser=require('./routes/findUser')
server.use('/contacts',createUser)
server.use('/',findUser)
server.listen(3001,()=>console.log('server started'))